module.exports = {
  "/blog/accessibility-wcag-aoda-presentation-follow": "/accessibility-wcag-aoda-presentation.html",
  "/blog/birth-merlin": "/blog/birth-merlin.html",
  "/blog/decoupling-drupal": "/blog/decoupling-drupal.html",
  "/about-us": "/about-us.html",
  "/mobile-web": "/work.html",
  "/meet-the-team": "/about-us.html",
  "/protfolio": "/work.html",
  "/contact": "/contact.html",
  "/brand/loblaws": "/work.html",
  "/brand/unifor": "/work.html",
  "/brand/canada-lands": "/work.html",
  "/portfolio/slide/125/all": "/work.html",
  "/portfolio/slide/129/all": "/work.html",
  "/portfolio/slide/131/all": "/work.html",
  "/cupw": "/work.html",
  "/youre-agency": "/contact.html",
  "/website-content-management": "/services.html",
  "/brand/allseating": "/allseating.html",
  "/sites/default/files/do-the-right-thing-slides.pdf": "/do-the-right-thing-slides.pdf",
};
